plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.openai.pokeballmouse'
    compileSdk 36

    defaultConfig {
        applicationId 'pl.openai.pokeballmouse'
        minSdk 29
        targetSdk 36
        versionCode 24
        versionName '0.7.1'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
